use rdev::{Button, Key};

pub fn key_name(key: &Key) -> Option<String> {
    match key {
        Key::Alt => Some("alt_l"),
        Key::AltGr => Some("alt_r"),
        Key::Backspace => Some("backspace"),
        Key::CapsLock => Some("caps_lock"),
        Key::ControlLeft => Some("ctrl_l"),
        Key::ControlRight => Some("ctrl_r"),
        Key::Delete => Some("delete"),
        Key::DownArrow => Some("down"),
        Key::End => Some("end"),
        Key::Escape => Some("esc"),
        Key::F1 => Some("f1"),
        Key::F2 => Some("f2"),
        Key::F3 => Some("f3"),
        Key::F4 => Some("f4"),
        Key::F5 => Some("f5"),
        Key::F6 => Some("f6"),
        Key::F7 => Some("f7"),
        Key::F8 => Some("f8"),
        Key::F9 => Some("f9"),
        Key::F10 => Some("f10"),
        Key::F11 => Some("f11"),
        Key::F12 => Some("f12"),
        Key::Home => Some("home"),
        Key::Insert => Some("insert"),
        Key::LeftArrow => Some("left"),
        Key::MetaLeft => Some("meta"),
        Key::MetaRight => Some("meta_r"),
        Key::NumLock => Some("numpad_lock"),
        Key::PageDown => Some("page_down"),
        Key::PageUp => Some("page_up"),
        Key::Pause => Some("pause"),
        Key::PrintScreen => Some("print_screen"),
        Key::Return => Some("enter"),
        Key::RightArrow => Some("right"),
        Key::ScrollLock => Some("scroll_lock"),
        Key::ShiftLeft => Some("shift_l"),
        Key::ShiftRight => Some("shift_r"),
        Key::Space => Some("space"),
        Key::Tab => Some("tab"),
        Key::UpArrow => Some("up"),

        Key::KeyA => Some("a"),
        Key::KeyB => Some("b"),
        Key::KeyC => Some("c"),
        Key::KeyD => Some("d"),
        Key::KeyE => Some("e"),
        Key::KeyF => Some("f"),
        Key::KeyG => Some("g"),
        Key::KeyH => Some("h"),
        Key::KeyI => Some("i"),
        Key::KeyJ => Some("j"),
        Key::KeyK => Some("k"),
        Key::KeyL => Some("l"),
        Key::KeyM => Some("m"),
        Key::KeyN => Some("n"),
        Key::KeyO => Some("o"),
        Key::KeyP => Some("p"),
        Key::KeyQ => Some("q"),
        Key::KeyR => Some("r"),
        Key::KeyS => Some("s"),
        Key::KeyT => Some("t"),
        Key::KeyU => Some("u"),
        Key::KeyV => Some("v"),
        Key::KeyW => Some("w"),
        Key::KeyX => Some("x"),
        Key::KeyY => Some("y"),
        Key::KeyZ => Some("z"),

        Key::Num0 => Some("0"),
        Key::Num1 => Some("1"),
        Key::Num2 => Some("2"),
        Key::Num3 => Some("3"),
        Key::Num4 => Some("4"),
        Key::Num5 => Some("5"),
        Key::Num6 => Some("6"),
        Key::Num7 => Some("7"),
        Key::Num8 => Some("8"),
        Key::Num9 => Some("9"),

        Key::BackQuote => Some("`"),
        Key::Minus => Some("-"),
        Key::Equal => Some("="),
        Key::LeftBracket => Some("["),
        Key::RightBracket => Some("]"),
        Key::SemiColon => Some(";"),
        Key::Quote => Some("'"),
        Key::BackSlash => Some("backslash"),
        Key::IntlBackslash => Some("intl_backslash"),
        Key::Comma => Some(","),
        Key::Dot => Some("."),
        Key::Slash => Some("/"),

        Key::Kp0 => Some("numpad0"),
        Key::Kp1 => Some("numpad1"),
        Key::Kp2 => Some("numpad2"),
        Key::Kp3 => Some("numpad3"),
        Key::Kp4 => Some("numpad4"),
        Key::Kp5 => Some("numpad5"),
        Key::Kp6 => Some("numpad6"),
        Key::Kp7 => Some("numpad7"),
        Key::Kp8 => Some("numpad8"),
        Key::Kp9 => Some("numpad9"),
        Key::KpReturn => Some("numpad_enter"),
        Key::KpMinus => Some("numpad_subtract"),
        Key::KpPlus => Some("numpad_add"),
        Key::KpMultiply => Some("numpad_multiply"),
        Key::KpDivide => Some("numpad_divide"),
        Key::KpDelete => Some("numpad_decimal"),

        Key::Function => Some("fn"),

        Key::Unknown(vk) => vk_name(*vk),
    }
    .map(String::from)
}

pub fn button_name(button: &Button) -> String {
    match button {
        Button::Left => "mouse_left",
        Button::Right => "mouse_right",
        Button::Middle => "mouse_middle",
        Button::Unknown(1) => "mouse_x1",
        Button::Unknown(2) => "mouse_x2",
        Button::Unknown(vk) => return format!("mouse_unknown_{}", vk),
    }
    .to_string()
}

pub fn vk_name(vk: u32) -> Option<&'static str> {
    match vk {
        48 => Some("0"), 49 => Some("1"), 50 => Some("2"), 51 => Some("3"),
        52 => Some("4"), 53 => Some("5"), 54 => Some("6"), 55 => Some("7"),
        56 => Some("8"), 57 => Some("9"),
        96 => Some("numpad0"), 97 => Some("numpad1"), 98 => Some("numpad2"),
        99 => Some("numpad3"), 100 => Some("numpad4"), 101 => Some("numpad5"),
        102 => Some("numpad6"), 103 => Some("numpad7"), 104 => Some("numpad8"),
        105 => Some("numpad9"),
        106 => Some("numpad_multiply"), 107 => Some("numpad_add"),
        109 => Some("numpad_subtract"), 110 => Some("numpad_decimal"),
        111 => Some("numpad_divide"), 144 => Some("numpad_lock"),
        65 => Some("a"), 66 => Some("b"), 67 => Some("c"), 68 => Some("d"),
        69 => Some("e"), 70 => Some("f"), 71 => Some("g"), 72 => Some("h"),
        73 => Some("i"), 74 => Some("j"), 75 => Some("k"), 76 => Some("l"),
        77 => Some("m"), 78 => Some("n"), 79 => Some("o"), 80 => Some("p"),
        81 => Some("q"), 82 => Some("r"), 83 => Some("s"), 84 => Some("t"),
        85 => Some("u"), 86 => Some("v"), 87 => Some("w"), 88 => Some("x"),
        89 => Some("y"), 90 => Some("z"), 91 => Some("meta"),
        19 => Some("pause"), 34 => Some("page_down"), 33 => Some("page_up"),
        35 => Some("end"), 36 => Some("home"), 237 => Some("fn"),
        8 => Some("backspace"), 9 => Some("tab"), 13 => Some("enter"),
        20 => Some("caps_lock"), 27 => Some("esc"), 32 => Some("space"),
        16 => Some("shift"), 160 => Some("shift_l"), 161 => Some("shift_r"),
        17 => Some("ctrl"), 162 => Some("ctrl_l"), 163 => Some("ctrl_r"),
        18 => Some("alt"), 164 => Some("alt_l"), 165 => Some("alt_r"),
        93 => Some("menu"),
        186 => Some(";"), 187 => Some("="), 188 => Some(","), 189 => Some("-"),
        190 => Some("."), 191 => Some("/"), 192 => Some("`"),
        219 => Some("["), 220 => Some("backslash"), 221 => Some("]"), 222 => Some("'"),
        112 => Some("f1"), 113 => Some("f2"), 114 => Some("f3"), 115 => Some("f4"),
        116 => Some("f5"), 117 => Some("f6"), 118 => Some("f7"), 119 => Some("f8"),
        120 => Some("f9"), 121 => Some("f10"), 122 => Some("f11"), 123 => Some("f12"),
        _ => None,
    }
}
